/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_autch_android_fluidballsgl_FluidBallsRenderer */

#ifndef _Included_net_autch_android_fluidballsgl_FluidBallsRenderer
#define _Included_net_autch_android_fluidballsgl_FluidBallsRenderer
#ifdef __cplusplus
extern "C" {
#endif
#undef net_autch_android_fluidballsgl_FluidBallsRenderer_BALLS
#define net_autch_android_fluidballsgl_FluidBallsRenderer_BALLS 500L
/*
 * Class:     net_autch_android_fluidballsgl_FluidBallsRenderer
 * Method:    fluidballs_init
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_autch_android_fluidballsgl_FluidBallsRenderer_fluidballs_1init
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     net_autch_android_fluidballsgl_FluidBallsRenderer
 * Method:    fluidballs_exit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_autch_android_fluidballsgl_FluidBallsRenderer_fluidballs_1exit
  (JNIEnv *, jobject);

/*
 * Class:     net_autch_android_fluidballsgl_FluidBallsRenderer
 * Method:    fluidballs_setaccel
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_net_autch_android_fluidballsgl_FluidBallsRenderer_fluidballs_1setaccel
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     net_autch_android_fluidballsgl_FluidBallsRenderer
 * Method:    fluidballs_drawballs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_autch_android_fluidballsgl_FluidBallsRenderer_fluidballs_1drawballs
  (JNIEnv *, jobject);

/*
 * Class:     net_autch_android_fluidballsgl_FluidBallsRenderer
 * Method:    fluidballs_getballpos
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_net_autch_android_fluidballsgl_FluidBallsRenderer_fluidballs_1getballpos
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     net_autch_android_fluidballsgl_FluidBallsRenderer
 * Method:    fluidballs_update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_autch_android_fluidballsgl_FluidBallsRenderer_fluidballs_1update
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
